// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzmC3ThAHziWBbluzohh735Eyb-sJoO6k',
    appId: '1:295585006212:web:29f0f0578717a1b1ed78d1',
    messagingSenderId: '295585006212',
    projectId: 'bgmi-tournamentor',
    authDomain: 'bgmi-tournamentor.firebaseapp.com',
    storageBucket: 'bgmi-tournamentor.firebasestorage.app',
    measurementId: 'G-HNC4PB1WQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYyIbIfcgjXMSIYo63EmJDrfQYMZR1m7k',
    appId: '1:295585006212:android:b0cd83305f6a26fced78d1',
    messagingSenderId: '295585006212',
    projectId: 'bgmi-tournamentor',
    storageBucket: 'bgmi-tournamentor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxdsWVDomNpHJVWXUyS1nRG_P4-nkfnMI',
    appId: '1:295585006212:ios:65e39916166261eced78d1',
    messagingSenderId: '295585006212',
    projectId: 'bgmi-tournamentor',
    storageBucket: 'bgmi-tournamentor.firebasestorage.app',
    iosBundleId: 'com.tournamentor.bgmi.bgmiTournamentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxdsWVDomNpHJVWXUyS1nRG_P4-nkfnMI',
    appId: '1:295585006212:ios:65e39916166261eced78d1',
    messagingSenderId: '295585006212',
    projectId: 'bgmi-tournamentor',
    storageBucket: 'bgmi-tournamentor.firebasestorage.app',
    iosBundleId: 'com.tournamentor.bgmi.bgmiTournamentor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzmC3ThAHziWBbluzohh735Eyb-sJoO6k',
    appId: '1:295585006212:web:50a1d191003a9f00ed78d1',
    messagingSenderId: '295585006212',
    projectId: 'bgmi-tournamentor',
    authDomain: 'bgmi-tournamentor.firebaseapp.com',
    storageBucket: 'bgmi-tournamentor.firebasestorage.app',
    measurementId: 'G-ETC4REN9RV',
  );
}
